### ISSUE TITLE
Get feedback on writing to other mapsets on ML

### ISSUE THREAD

**Issue by ninsbl** [NikosAlexandris/i.landsat.import#2]
I understand your motivation for importing different scenes into different mapsets. And it can make some workflows more convenient. However, writing to other mapsets (except for temporary) is somewhat against basic principles in GRASS if I understood correctly.
The only module I know of that does it is i.ortho.rectify, that by definition is "cross-location" and thus "cross-mapsets".
I would suggest discussing that concept of importing to different mapsets on ML....

**Comment by NikosAlexandris** [comment]
It is, somehow, practical. Perhaps the import in one, or the PERMANENT, Mapset, could be the default. Then have a flag to split in independent Mapsets.

If it will be of interest to more/many, the module could eventually land in the addons repository.

**Comment by ninsbl** [comment]
Yes, the module looks definitely very useful!

**Comment by NikosAlexandris** [comment]
Feedback asked :-)

**Comment by NikosAlexandris** [comment]
For completeness, linking to the relevant thread/post: https://lists.osgeo.org/pipermail/grass-dev/2017-November/086577.html.

It still would be useful to "agree" on what the default setting would be for when importing multiple scenes: one Mapset for all of them or multiple independent Mapsets for each scene.

**Comment by ninsbl** [comment]
That depends on the use case you have in mind I would say.
Personally, I would probably use "import everything to current mapset" as default, and make generation of mapsets per scene a flag, assuming the following workflow:

For parallelizing the whole processing chain based on scenes (one process per path/row), I would write job-scripts that do what I want to do with the data (import, quality filter, image corrections/enhancements, ...). Such a job-script would take path/row as a variable and each process can run in a dedicated mapset. Then importing to other mapsets would be less relevant then.

But if you you do the importing as an isolated, possibly single threaded first step things can be different. There I would assume that downloading is the bottleneck and you would not want many cores to wait for the data from the internet...

**Comment by NikosAlexandris** [comment]
Truth told, sub-consciously, I built the script to suit my needs. The point is to serve the interest of many. In general, I follow the approach you describe. As mentioned at https://lists.osgeo.org/pipermail/grass-dev/2017-November/086456.html. Once mature and if useful, I'll share the scripted workflow.

Ideas "stolen" from your last comment:
- I use GNU Parallel often. Can we recommend its installation and integrate its use in GRASS-GIS addons?
- For example, via a flag, let the creation of multiple Mapsets be run in parallel. Offer an option for the number of cores, and similar.

**Comment by ninsbl** [comment]
GNU parallel is nice (I use it myself quite often - or more precisely xargs), but unfortunately not platform independent.
There are several options for parallel processing in Python, among them
 - plain multiprocessing in Python [1]
 - the GRASS specific ParallelModuleQueue [2]

1:https://docs.python.org/2/library/multiprocessing.html
2:https://grass.osgeo.org/grass73/manuals/libpython/pygrass.modules.interface.html?highlight=parallelmodulequeue#pygrass.modules.interface.module.ParallelModuleQueue
